# Generated by Django 4.2.6 on 2023-11-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0002_customer_inventory_servicepack_vehicle_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Appointmrnt_ID',
            new_name='AppointmentID',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Unitprice',
            new_name='UnitPrice',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='CusttomerID',
            new_name='CustomerID',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='VehhicleID',
            new_name='VehicleID',
        ),
    ]
