# Generated by Django 4.2.6 on 2023-11-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0003_rename_appointmrnt_id_appointment_appointmentid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='EmpID',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
