# Generated by Django 4.2.6 on 2023-11-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0004_remove_employee_id_employee_empid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='EmpID',
        ),
        migrations.AddField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
