# Generated by Django 4.2.6 on 2023-11-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0011_remove_appointment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepack',
            old_name='Description',
            new_name='Summary',
        ),
    ]
