# Generated by Django 4.2.6 on 2023-11-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0012_rename_description_servicepack_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepack',
            old_name='Summary',
            new_name='Description',
        ),
    ]
