# Generated by Django 4.2.6 on 2023-11-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0014_alter_employee_workshedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='ServiceID',
            new_name='PackageID',
        ),
    ]
