# Generated by Django 4.2.6 on 2023-11-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0015_rename_serviceid_appointment_packageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Contact',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='FirstName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='LastName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='FirstName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='LastName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='WorkShedule',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Quantity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='PaymentMethod',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicepack',
            name='Description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicepack',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Licenseplate',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Modal',
            field=models.CharField(max_length=200),
        ),
    ]
